/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cz.vondr.junit.issue

import org.junit.jupiter.api.Test


class LibraryTest {

    @Test
    fun testSomeLibraryMethod() {
        println("TEST EXECUTED!!!")
    }
}
